version: "3.8"

services:
  app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/.env.prod
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: always

  mysql:
    container_name: knowledge_base_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - config/.env.prod
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
